// src/data/dummy_course_data.js

const dummy_course_data = [
    {
      id: 1,
      title: 'Introducción a Python - Nivel 1',
      description: 'Un curso básico para comenzar a programar en Python.',
      image: 'https://example.com/python-course1.jpg',
      category: 'Python',
      price: 29.99,
      level: 1,
    },
    {
      id: 2,
      title: 'Python Intermedio - Nivel 2',
      description: 'Amplía tus conocimientos de Python con este curso intermedio.',
      image: 'https://example.com/python-course2.jpg',
      category: 'Python',
      price: 39.99,
      level: 2,
    },
    {
      id: 3,
      title: 'Python Avanzado - Nivel 3',
      description: 'Domina Python y sus aplicaciones avanzadas.',
      image: 'https://example.com/python-course3.jpg',
      category: 'Python',
      price: 49.99,
      level: 3,
    },
    {
      id: 4,
      title: 'Introducción a JavaScript - Nivel 1',
      description: 'Aprende JavaScript desde cero y comienza a crear tus primeras aplicaciones web.',
      image: 'https://example.com/javascript-course1.jpg',
      category: 'JavaScript',
      price: 29.99,
      level: 1,
    },
    {
      id: 5,
      title: 'JavaScript Intermedio - Nivel 2',
      description: 'Profundiza en JavaScript y sus funcionalidades intermedias.',
      image: 'https://example.com/javascript-course2.jpg',
      category: 'JavaScript',
      price: 39.99,
      level: 2,
    },
    {
      id: 6,
      title: 'JavaScript Avanzado - Nivel 3',
      description: 'Conviértete en un experto en JavaScript con este curso avanzado.',
      image: 'https://example.com/javascript-course3.jpg',
      category: 'JavaScript',
      price: 49.99,
      level: 3,
    },
    {
      id: 7,
      title: 'Introducción a Java - Nivel 1',
      description: 'Un curso para comenzar a programar en Java.',
      image: 'https://example.com/java-course1.jpg',
      category: 'Java',
      price: 29.99,
      level: 1,
    },
    {
      id: 8,
      title: 'Java Intermedio - Nivel 2',
      description: 'Mejora tus habilidades en Java con este curso intermedio.',
      image: 'https://example.com/java-course2.jpg',
      category: 'Java',
      price: 39.99,
      level: 2,
    },
    {
      id: 9,
      title: 'Java Avanzado - Nivel 3',
      description: 'Domina Java y sus aplicaciones en desarrollo empresarial.',
      image: 'https://example.com/java-course3.jpg',
      category: 'Java',
      price: 49.99,
      level: 3,
    },
    {
      id: 10,
      title: 'Introducción a C# - Nivel 1',
      description: 'Un curso básico para aprender C#.',
      image: 'https://example.com/csharp-course1.jpg',
      category: 'C#',
      price: 29.99,
      level: 1,
    },
    {
      id: 11,
      title: 'C# Intermedio - Nivel 2',
      description: 'Desarrolla tus habilidades en C# con este curso intermedio.',
      image: 'https://example.com/csharp-course2.jpg',
      category: 'C#',
      price: 39.99,
      level: 2,
    },
    {
      id: 12,
      title: 'C# Avanzado - Nivel 3',
      description: 'Domina C# y sus frameworks avanzados.',
      image: 'https://example.com/csharp-course3.jpg',
      category: 'C#',
      price: 49.99,
      level: 3,
    },
    {
      id: 13,
      title: 'Introducción a Ruby - Nivel 1',
      description: 'Aprende Ruby desde cero y comienza a desarrollar aplicaciones.',
      image: 'https://example.com/ruby-course1.jpg',
      category: 'Ruby',
      price: 29.99,
      level: 1,
    },
    {
      id: 14,
      title: 'Ruby Intermedio - Nivel 2',
      description: 'Profundiza en Ruby y sus aplicaciones intermedias.',
      image: 'https://example.com/ruby-course2.jpg',
      category: 'Ruby',
      price: 39.99,
      level: 2,
    },
    {
      id: 15,
      title: 'Ruby Avanzado - Nivel 3',
      description: 'Conviértete en un experto en Ruby y sus mejores prácticas.',
      image: 'https://example.com/ruby-course3.jpg',
      category: 'Ruby',
      price: 49.99,
      level: 3,
    },
  ];
  
  export default dummy_course_data;
  