const listaMensajes = [
  '"Cada línea de código que escribes hoy es una puerta que abres hacia nuevas oportunidades mañana."',
  '"No se trata de aprenderlo todo de una vez, sino de avanzar cada día un poco más que ayer."',
  '"Recuerda: incluso los mejores desarrolladores comenzaron sin saber nada. ¡Sigue adelante!"',
  '"Aprender a programar no solo te enseña a hablar con las máquinas, sino a pensar de una forma más creativa y lógica."',
  '"Resolver errores es parte del viaje. Cada bug que arreglas te hace más fuerte y más hábil."',
  '"La programación es el superpoder de crear algo de la nada. ¡Nunca subestimes lo que puedes construir!"',
  '"No importa cuántas veces falles, lo importante es cuánto aprendes y cómo te levantas."',
  '"No necesitas ser un genio para programar; solo necesitas la voluntad de resolver problemas."',
  '"El código es como un rompecabezas: desafiante, pero increíblemente satisfactorio cuando ves la imagen completa."',
  '"¿Te imaginas cuántas vidas puedes cambiar con lo que construyas? ¡El mundo necesita tu código!"',
  '"Comienza donde estés, usa lo que tengas, haz lo que puedas… y sigue codificando."',
  '"El camino no siempre será fácil, pero cada proyecto terminado es una victoria que vale la pena celebrar."',
  '"Si alguna vez te sientes frustrado, recuerda: incluso los errores son pasos hacia el dominio del código."',
  '"Cada vez que te sientas atascado, estás a punto de aprender algo nuevo. ¡No te rindas!"',
  '"Nunca sabes cuándo el proyecto que iniciaste como principiante se convertirá en la próxima gran idea."',
  '"Cada vez que aprendes algo nuevo, estás expandiendo los límites de lo que creías posible."',
  '"No te compares con otros programadores, compárate con el que eras ayer."',
  '"La programación no se trata de memorizar, se trata de encontrar soluciones creativas."',
  '"Cada error es una lección disfrazada; ¡siéntete orgulloso de los errores que cometes!"',
  '"Nunca subestimes el poder de la curiosidad: una pregunta puede abrir la puerta a infinitas respuestas."',
  '"Lo que hoy parece complicado, mañana será solo un paso más en tu camino de aprendizaje."',
  '"El viaje de ser programador nunca termina, y eso es lo emocionante: siempre hay algo nuevo por descubrir."',
  '"Nunca dejes que un desafío te haga dudar de tu potencial. ¡Tienes todo lo necesario para superarlo!"',
  '"No importa si tu código es perfecto; importa cuánto te esfuerces por mejorarlo."',
  '"Cada proyecto pequeño te acerca a grandes logros. ¡Sigue construyendo!"',
  '"No es magia, es lógica. No es suerte, es práctica. La programación es el arte de convertir ideas en realidad."',
  '"Aprender a programar es como aprender un nuevo idioma: la práctica constante te llevará a la fluidez."',
  '"El código es una extensión de tu pensamiento. ¡Cada línea es una oportunidad de expresar creatividad!"',
  '"Sigue soñando en grande y construyendo con paciencia. ¡Las mejores cosas toman tiempo!"',
  '"No temas pedir ayuda. La comunidad de desarrolladores está aquí para apoyarte y crecer juntos."',
  '"Cada problema tiene una solución; lo importante es no rendirse hasta encontrarla."',
  '"Los errores no son el fin del camino, son oportunidades disfrazadas de aprendizaje."',
  '"La curiosidad es el primer paso para resolver cualquier problema. Pregunta, investiga, y aprende."',
  '"Cada día es una nueva oportunidad para mejorar tus habilidades y crecer como programador."',
  '"El código que escribes hoy es una huella de tu crecimiento personal y profesional."',
  '"Desarrollar es un arte que requiere tiempo, esfuerzo y, sobre todo, pasión."',
  '"Los grandes desarrolladores son aquellos que nunca dejan de aprender y adaptarse."',
  '"Construir algo significativo requiere esfuerzo, pero cada paso cuenta."',
  '"Cada proyecto es una oportunidad para dejar tu marca en el mundo digital."',
  '"En la programación, la perseverancia es más importante que la perfección."',
  '"No olvides celebrar tus logros, por pequeños que sean; cada uno es un paso hacia adelante."',
  '"Las mejores ideas a menudo surgen de la colaboración y el intercambio de conocimientos."',
  '"La tecnología cambia rápidamente, pero tu pasión por aprender debe ser constante."',
  '"La programación es un viaje, no un destino; disfruta del proceso de aprender y crear."',
  '"Cada día, el código que escribes puede inspirar a otros a soñar en grande."',
  '"Nunca subestimes el impacto que tu trabajo puede tener en la vida de otros."',
  '"Recuerda: el verdadero éxito no se mide por el reconocimiento, sino por la satisfacción de resolver problemas."',
  '"Cada línea de código es una oportunidad para dejar una huella positiva en el mundo."',
  '"Las mejores soluciones a menudo provienen de pensar fuera de la caja. ¡Atrévete a innovar!"',
  '"Tu pasión por programar es el motor que impulsará tus proyectos hacia el éxito."',
  '"La programación es un viaje continuo; cada día trae nuevas lecciones y oportunidades."',
  '"La creatividad es tan importante como la lógica en la programación; combínalas para obtener resultados sorprendentes."',
  '"No temas experimentar; a menudo, los mejores resultados provienen de la exploración y la curiosidad."',
  '"Cada proyecto terminado es una prueba de tu dedicación y habilidades. ¡Sigue creando!"',
  '"Cada línea de código es un paso más hacia un futuro lleno de posibilidades."',
  '"Estudiar programación te abre las puertas a un mundo de innovación y creatividad."',
  '"No subestimes tu capacidad de aprender; la programación es un viaje que vale la pena."',
  '"Cada programador fue una vez un principiante. ¡Hoy es el día perfecto para comenzar!"',
  '"La programación no solo es una habilidad; es una forma de pensar y resolver problemas."',
  '"Cada nuevo concepto que aprendes es un ladrillo en la construcción de tu carrera."',
  '"Recuerda que cada error es una oportunidad para aprender algo nuevo."',
  '"La curiosidad es tu mejor aliada en el mundo de la programación. Nunca dejes de preguntar."',
  '"La programación te da el poder de construir tus propias herramientas y aplicaciones."',
  '"Dedica un poco de tiempo cada día a estudiar y verás grandes progresos con el tiempo."',
  '"La clave del éxito en programación es la práctica constante y la perseverancia."',
  '"No te preocupes por ser perfecto; lo importante es seguir avanzando y aprendiendo."',
  '"Cada vez que resuelves un problema, te vuelves un mejor programador."',
  '"Estudiar programación es una inversión en tu futuro y en el de los demás."',
  '"Nunca dejes que la complejidad te desanime; cada gran proyecto comienza con pasos pequeños."',
  '"Cada desafío que enfrentas es una oportunidad para crecer y mejorar tus habilidades."',
  '"La programación es una habilidad invaluable en el mundo moderno. ¡Aprovecha esa oportunidad!"',
  '"Tus ideas pueden cambiar el mundo; aprender a programar es el primer paso para realizarlas."',
  '"Estudia programación y conviértete en el arquitecto de tu propio destino."',
  '"Cada línea de código que escribes puede tener un impacto positivo en la vida de alguien."',
  '"Recuerda: el éxito en la programación se construye a través de la práctica y la dedicación."',
  '"La programación no es solo para los genios; es para cualquiera que esté dispuesto a aprender."',
  '"La perseverancia es la clave; incluso los más grandes programadores enfrentaron desafíos."',
  '"Tu camino en la programación será único; no lo compares con el de los demás."',
  '"El aprendizaje nunca se detiene; cada día trae nuevas oportunidades para mejorar."',
  '"Confía en ti mismo y en tu capacidad para resolver problemas. ¡Tú puedes!"',
  '"Cada proyecto que completes te acercará más a tus metas como programador."',
  '"Estudiar programación es un viaje emocionante que te llevará a lugares inesperados."',
  '"No tengas miedo de pedir ayuda; la comunidad de programadores está aquí para apoyarte."',
  '"Tu pasión por la programación es el motor que impulsará tu crecimiento personal y profesional."',
  '"Cada vez que dominas un nuevo concepto, amplías tus horizontes como desarrollador."',
  '"Los problemas son oportunidades disfrazadas; enfréntalos con determinación."',
  '"La programación es un arte que requiere tiempo, práctica y mucha creatividad."',
  '"Cada nuevo lenguaje que aprendes es una herramienta más en tu caja de herramientas."',
  '"La tecnología avanza rápidamente; mantente al día y sigue aprendiendo."',
  '"La programación es un superpoder que te permite transformar ideas en realidad."',
  '"No importa cuán difícil parezca, cada día es una oportunidad para mejorar."',
  '"La práctica hace al maestro; dedica tiempo a practicar y verás resultados."',
  '"Cada línea de código es una oportunidad para ser creativo y hacer algo extraordinario."',
  '"El aprendizaje es un proceso continuo; no te desanimes si no entiendes algo de inmediato."',
  '"Cada vez que resuelves un problema, contribuyes al mundo de la tecnología."',
  '"Recuerda: cada programador ha estado donde tú estás ahora. ¡Sigue adelante!"',
  '"Tu esfuerzo y dedicación te llevarán lejos en el mundo de la programación."',
  '"No hay límites para lo que puedes lograr si te dedicas a aprender y crecer."',
  '"La programación te ofrece herramientas para hacer del mundo un lugar mejor."',
  '"Cada nueva habilidad que adquieras te hará más valioso en el mercado laboral."',
  '"La pasión por aprender es la clave del éxito en la programación."',
  '"Tu historia como programador está en tus manos. ¡Escribe un gran capítulo hoy!"',
  '"No importa cuántas veces caigas; lo importante es levantarte y seguir intentando."',
  '"La programación te enseña a pensar de manera lógica y estructurada."',
  '"Aprovecha cada oportunidad de aprender, ya sea a través de libros, cursos o proyectos."',
  '"Recuerda que el aprendizaje es un viaje, no un destino. Disfruta cada paso."',
  '"No te detengas; cada día trae nuevas oportunidades para crecer como programador."',
  '"Con paciencia y práctica, dominarás cualquier lenguaje de programación que elijas."',
  '"El esfuerzo que pones hoy te recompensará en el futuro. ¡Sigue adelante!"',
  '"Cada día que estudias programación es un día más cerca de tus metas."',
];

export default listaMensajes;
